[theme]
# Define o tema base como escuro, que o servidor vai ler
base="dark"

# Define a cor primária (verde Petrobras)
primaryColor="#00A859"

# Cores de fundo e texto para o tema escuro
backgroundColor="#0E1117"
secondaryBackgroundColor="#262730"
textColor="#FAFAFA"
font="sans serif"