[theme]
# Tema base escuro
base="dark"

# Cor primária (filtros, botões, etc.) - Amarelo Petrobras
primaryColor="#FFC700"

# Cor de fundo principal - Cinza bem escuro
backgroundColor="#0E1117"

# Cor de fundo secundária (barra lateral e interior dos cartões) - Cinza um pouco mais claro
secondaryBackgroundColor="#262730"

# Cor do texto principal - Branco suave
textColor="#FAFAFA"

# Fonte padrão
font="sans serif"