[theme]
# Tema base claro para máxima legibilidade
base="light"

# Cor primária (filtros, botões, etc.) - Verde Petrobras
primaryColor="#00A859"

# Fundo principal da aplicação - um branco suave
backgroundColor="#FAFAFA"

# Fundo secundário (interior dos cartões e da barra lateral) - branco puro
secondaryBackgroundColor="#FFFFFF"

# Cor do texto principal - quase preto para alto contraste
textColor="#0E1117"

font="sans serif"