[theme]
# Define o tema base como claro
base="light"

# Cor primária (usada nos filtros, botões, etc.) - Verde Petrobras
primaryColor="#00A859"

# Cor do fundo principal da aplicação - Cinza muito claro, mais suave que branco puro
backgroundColor="#F0F2F6"

# Cor de fundo de elementos secundários (barra lateral, interior dos cartões) - Branco
secondaryBackgroundColor="#FFFFFF"

# Cor do texto principal - Cinza escuro
textColor="#262730"

# Fonte padrão
font="sans serif"